server:
  port: 8081


spring:

  # 配置模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8

  # 配置资源
  resources:
    static-locations: classpath:/static/,file:E:/upload/

  # 配置数据库信息
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/videotest?useSSL=false
      username: root
      password: root


web_config:
  upload_path: E:/upload/


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl